### ISSUE TITLE
ImportError: No module named 'bleu'

### ISSUE THREAD

**Issue by EMCL** [YuanEZhou/show-attend-and-tell#3]
hi,
i am getting blow error..when run the train.py.
Traceback (most recent call last):
  File "train.py", line 1, in <module>
    from core.solver import CaptioningSolver
  File "D:\Show_attend\showAttendAndTell\show-attend-and-tell-tensorflow\core\solver.py", line 10, in <module>
    from bleu import evaluate
ImportError: No module named 'bleu'

**Comment by tanishqhooda** [comment]
How did you resolve this?
